[Utilities]
; Each program below may be set either as an absolute path (e.g.
; "C:\Program Files\7-Zip\7z.exe") or as a command available in the PATH (e.g. 7z).

ISCC="C:\Program Files (x86)\Inno Setup 5\iscc.exe"

;
; You don't need to modify anything below this line
;

[Directories]
; Output
SETUP_INPUT_DIR=..\..\setup\builder
