[Toolchains]
TOOLCHAINS32_VERSIONS=950WINXP;1050
GDB32_VERSION=10.2
TOOLCHAINS64_VERSIONS=1340;1440;1530;1620;LEGACY;STABLE
GDB64_VERSION=17.1

[Toolchains32]
; Toolchains: 9.5.0-winxp
TOOLCHAINS32_VERSION_NAME_950WINXP=9.5.0-winxp
TOOLCHAINS32_VERSION_DESC_950WINXP=This legacy toolchain is based on GCC 9.5.0 with Newlib 4.3.0.20230120. This was the previous, officially supported toolchains for the past decade.
TOOLCHAINS32_VERSION_PACKAGE_ARMEABI_950WINXP=arm-eabi-20231003-gcc-8.5.0-binutils-2.34
TOOLCHAINS32_VERSION_PACKAGE_SHELF_950WINXP=sh-elf-20250704-gcc-9.5.0-binutils-2.34-newlib-4.3.0.20230120
; Toolchains: 10.5.0
TOOLCHAINS32_VERSION_NAME_1050=10.5.0
TOOLCHAINS32_VERSION_DESC_1050=This toolchain is based on GCC 10.5.0 with Newlib 4.3.0.20230120.
TOOLCHAINS32_VERSION_PACKAGE_ARMEABI_1050=arm-eabi-20231003-gcc-8.5.0-binutils-2.34
TOOLCHAINS32_VERSION_PACKAGE_SHELF_1050=sh-elf-20250707-gcc-10.5.0-binutils-2.34-newlib-4.3.0.20230120

[Toolchains64]
; Toolchains: 13.4.0
TOOLCHAINS64_VERSION_NAME_1340=13.4.0
TOOLCHAINS64_VERSION_DESC_1340=Testing: Latest release in the GCC 13 series, released 2025-06-05.
TOOLCHAINS64_VERSION_PACKAGE_ARMEABI_1340=arm-eabi-20250127-gcc-8.5.0-binutils-2.43.1-x64
TOOLCHAINS64_VERSION_PACKAGE_SHELF_1340=sh-elf-20260920-gcc-13.4.0-binutils-2.47-newlib-4.6.0.20260123-x64
; Toolchains: 14.4.0
TOOLCHAINS64_VERSION_NAME_1440=14.4.0
TOOLCHAINS64_VERSION_DESC_1440=Testing: Latest release in the GCC 14 series, released 2026-06-19.
TOOLCHAINS64_VERSION_PACKAGE_ARMEABI_1440=arm-eabi-20250127-gcc-8.5.0-binutils-2.43.1-x64
TOOLCHAINS64_VERSION_PACKAGE_SHELF_1440=sh-elf-20260924-gcc-14.4.0-binutils-2.47-newlib-4.6.0.20260123-x64
; Toolchains: 15.3.0
TOOLCHAINS64_VERSION_NAME_1530=15.3.0
TOOLCHAINS64_VERSION_DESC_1530=Testing: Latest release in the GCC 15 series, released 2026-06-12.
TOOLCHAINS64_VERSION_PACKAGE_ARMEABI_1530=arm-eabi-20250127-gcc-8.5.0-binutils-2.43.1-x64
TOOLCHAINS64_VERSION_PACKAGE_SHELF_1530=sh-elf-20260924-gcc-15.3.0-binutils-2.47-newlib-4.6.0.20260123-x64
; Toolchains: 16.2.0
TOOLCHAINS64_VERSION_NAME_1620=16.2.0
TOOLCHAINS64_VERSION_DESC_1620=Testing: Latest release in the GCC 16 series, released 2026-08-07.
TOOLCHAINS64_VERSION_PACKAGE_ARMEABI_1620=arm-eabi-20250127-gcc-8.5.0-binutils-2.43.1-x64
TOOLCHAINS64_VERSION_PACKAGE_SHELF_1620=sh-elf-20260919-gcc-16.2.0-binutils-2.47-newlib-4.6.0.20260123-x64
; Toolchains: Legacy
TOOLCHAINS64_VERSION_NAME_LEGACY=Legacy
TOOLCHAINS64_VERSION_DESC_LEGACY=Legacy: Previously designated stable, GCC 13.2.0, released 2023-07-27.
TOOLCHAINS64_VERSION_PACKAGE_ARMEABI_LEGACY=arm-eabi-20250127-gcc-8.5.0-binutils-2.43.1-x64
TOOLCHAINS64_VERSION_PACKAGE_SHELF_LEGACY=sh-elf-20250705-gcc-13.2.0-binutils-2.43-newlib-4.3.0.20230120-x64
; Toolchains: Stable
TOOLCHAINS64_VERSION_NAME_STABLE=Stable
TOOLCHAINS64_VERSION_DESC_STABLE=Well-tested; based on GCC 15.2.0, released 2025-08-08.
TOOLCHAINS64_VERSION_PACKAGE_ARMEABI_STABLE=arm-eabi-20250127-gcc-8.5.0-binutils-2.43.1-x64
TOOLCHAINS64_VERSION_PACKAGE_SHELF_STABLE=sh-elf-20260919-gcc-15.2.0-binutils-2.45.1-newlib-4.6.0.20260123-x64

[Base32]
; MinGW Base
MINGW32_BASE_VERSION=20231029
; MSYS Base components
MSYS32_BASE_BASH_VERSION=3.1.23-2
MSYS32_BASE_CURL_VERSION=7.79.1
MSYS32_BASE_DIRHASH_VERSION=1.11.0
MSYS32_BASE_GAWK_VERSION=4.0.1-2
MSYS32_BASE_LIBELF_VERSION=0.18.13
MSYS32_BASE_LIBJPEG_VERSION=9d
MSYS32_BASE_LIBPNG_VERSION=1.6.37
MSYS32_BASE_MINTTY_VERSION=3.5.0
MSYS32_BASE_CORE_EXTENDED_VERSION=1.0.19-2
MSYS32_BASE_WGET_VERSION=1.19.4

[Base64]
; MinGW-w64 Base
MINGW64_BASE_VERSION=20250825
; MSYS2 Base components
MSYS64_BASE_DIRHASH_VERSION=1.26.1

[Utilities]
; Essential external utilities
UTILITIES_CDRTOOLS_VERSION=2.01-bootcd.ru
UTILITIES_IMG4DC_VERSION=20120512

[Addons]
; Addons CLI
ADDONS_CMD_ELEVATE_VERSION=1.3
ADDONS_CMD_PVR2PNG_VERSION=1.01
ADDONS_CMD_TXFUTILS_VERSION=20011020
ADDONS_CMD_VMUTOOL_VERSION=1.0
; Addons GUI
ADDONS_GUI_BDREAMS_VERSION=1.0.6c-titan.fix
ADDONS_GUI_BUILDSBI_VERSION=3.2
ADDONS_GUI_CHECKER_VERSION=2.0.3a
ADDONS_GUI_IPWRITER_VERSION=0.1.6a
ADDONS_GUI_MRWRITER_VERSION=0.3
ADDONS_GUI_SBINDUCR_VERSION=5.0
ADDONS_GUI_VMUTOOL_VERSION=1.0
